In [51]:
import numpy as np
import neurolab as nl

In [57]:
#Образцы и ассоциации
n = 3
x = np.array([[1.,0.,0.,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,1], 
              [1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0],
              [1,1,1,1,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,1,1,1,1]])
d = np.array([[1, 1], [-1, -1], [-1, 1]])
x = x / np.linalg.norm(x)
x

array([[ 0.18569534,  0.        ,  0.        ,  0.        ,  0.18569534,
         0.        ,  0.18569534,  0.        ,  0.18569534,  0.        ,
         0.        ,  0.        ,  0.18569534,  0.        ,  0.        ,
         0.        ,  0.18569534,  0.        ,  0.18569534,  0.        ,
         0.18569534,  0.        ,  0.        ,  0.        ,  0.18569534],
       [ 0.18569534,  0.        ,  0.        ,  0.        ,  0.18569534,
         0.        ,  0.18569534,  0.        ,  0.18569534,  0.        ,
         0.        ,  0.        ,  0.18569534,  0.        ,  0.        ,
         0.        ,  0.        ,  0.18569534,  0.        ,  0.        ,
         0.        ,  0.        ,  0.18569534,  0.        ,  0.        ],
       [ 0.18569534,  0.18569534,  0.18569534,  0.18569534,  0.18569534,
         0.        ,  0.        ,  0.        ,  0.18569534,  0.        ,
         0.        ,  0.        ,  0.18569534,  0.        ,  0.        ,
         0.        ,  0.18569534,  0.        ,  0

In [58]:
#Создание линейного ассоциатора с пороговыми функциями активации
MyPerc = nl.net.newp(nl.tool.minmax(x), 2, nl.net.trans.HardLims())

In [59]:
w = np.zeros((2,25))
for i in range(25):
    for j in range(2):
        for k in range (n):
            w[j,i] += x[k,i]*d[k,j]
MyPerc.layers[0].np['w'] = w
MyPerc.layers[0].np['b'] = 0

In [60]:
#Опрос сети на исходных образцах
y = MyPerc.sim(x)
print(x)
print(y)

[[ 0.18569534  0.          0.          0.          0.18569534  0.
   0.18569534  0.          0.18569534  0.          0.          0.
   0.18569534  0.          0.          0.          0.18569534  0.
   0.18569534  0.          0.18569534  0.          0.          0.
   0.18569534]
 [ 0.18569534  0.          0.          0.          0.18569534  0.
   0.18569534  0.          0.18569534  0.          0.          0.
   0.18569534  0.          0.          0.          0.          0.18569534
   0.          0.          0.          0.          0.18569534  0.          0.        ]
 [ 0.18569534  0.18569534  0.18569534  0.18569534  0.18569534  0.          0.
   0.          0.18569534  0.          0.          0.          0.18569534
   0.          0.          0.          0.18569534  0.          0.          0.
   0.18569534  0.18569534  0.18569534  0.18569534  0.18569534]]
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]


In [61]:
#Опрос сети на искаженных образцах
xtest = x + np.eye(3,25)
y = MyPerc.sim(xtest)
print(xtest)
print(y)



[[ 1.18569534  0.          0.          0.          0.18569534  0.
   0.18569534  0.          0.18569534  0.          0.          0.
   0.18569534  0.          0.          0.          0.18569534  0.
   0.18569534  0.          0.18569534  0.          0.          0.
   0.18569534]
 [ 0.18569534  1.          0.          0.          0.18569534  0.
   0.18569534  0.          0.18569534  0.          0.          0.
   0.18569534  0.          0.          0.          0.          0.18569534
   0.          0.          0.          0.          0.18569534  0.          0.        ]
 [ 0.18569534  0.18569534  1.18569534  0.18569534  0.18569534  0.          0.
   0.          0.18569534  0.          0.          0.          0.18569534
   0.          0.          0.          0.18569534  0.          0.          0.
   0.18569534  0.18569534  0.18569534  0.18569534  0.18569534]]
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
