In [7]:
import numpy as np
import neurolab as nl
from sklearn.preprocessing import normalize

#Образцы и ассоциации
n = 4
x = np.array([[2., -1., 0., 0.], [1., 2., 0., 0.], [0., 0., 2., 1.], [0., 0., 1., -2.]])
d = np.array([[1, 1], [-1, -1], [1, -1], [-1, 1]])

x = x / np.linalg.norm(x)
x

array([[ 0.4472136, -0.2236068,  0.       ,  0.       ],
       [ 0.2236068,  0.4472136,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.4472136,  0.2236068],
       [ 0.       ,  0.       ,  0.2236068, -0.4472136]])

In [8]:
#Создание линейного ассоциатора с пороговыми функциями активации
MyPerc = nl.net.newp(nl.tool.minmax(x), 2, nl.net.trans.PureLin())
#Задание весов сети
w = np.zeros((2,4))
for i in range(4):
    for j in range(2):
        for k in range (n):
            w[j,i] += x[k,i]*d[k,j]
MyPerc.layers[0].np['w'] = w
MyPerc.layers[0].np['b'] = 0

In [9]:
#Опрос сети на исходных образцах
y = MyPerc.sim(x)
print(x)
print(y)

[[ 0.4472136 -0.2236068  0.         0.       ]
 [ 0.2236068  0.4472136  0.         0.       ]
 [ 0.         0.         0.4472136  0.2236068]
 [ 0.         0.         0.2236068 -0.4472136]]
[[ 0.25  0.25]
 [-0.25 -0.25]
 [ 0.25 -0.25]
 [-0.25  0.25]]


In [10]:
xtest = x + np.array([[0,0,0,1], [0,0,1,0], [0,1,0,0], [1,0,0,0]])
y = MyPerc.sim(xtest)
print(xtest)
print(y)

[[ 0.4472136 -0.2236068  0.         1.       ]
 [ 0.2236068  0.4472136  1.         0.       ]
 [ 0.         1.         0.4472136  0.2236068]
 [ 1.         0.         0.2236068 -0.4472136]]
[[ 0.92082039 -0.42082039]
 [-0.0263932  -0.4736068 ]
 [-0.42082039 -0.92082039]
 [-0.0263932   0.4736068 ]]
